---
downloads: ~/.ansible-downloads/

configure_dotfiles: true
configure_terminal: true
configure_osx: true

# Set to 'true' to configure the Dock via dockutil.
configure_dock: true
dockitems_remove: [TV, Podcasts, Safari]
# - Launchpad
# - TV
# - Podcasts
# - 'App Store'
dockitems_persist: []
# - name: "Sublime Text"
#   path: "/Applications/Sublime Text.app/"
#   pos: 5

configure_sudoers: true
sudoers_custom_config: |
  # Allow users in admin group to use sudo with no password.
  %admin ALL=(ALL) NOPASSWD: ALL
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

dotfiles_repo: https://github.com/geerlingguy/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/dotfiles-src
dotfiles_files:
  - .zshrc
  - .inputrc
  - .osx

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - autoconf
  - bash-completion
  - cmake
  - doxygen
  - gettext
  - ghex
  - gifsicle
  - git
  - github/gh/gh
  - go
  - gpg
  - graphviz
  - htop
  - httpie
  - hwloc
  - iperf
  - libevent
  - sqlite
  - llvm
  - mc
  - mcrypt
  - ninja
  - nmap
  - node
  - nvm
  - ssh-copy-id
  - stats
  - theseal/ssh-askpass/ssh-askpass
  - tree
  - cowsay
  - readline
  - openfortivpn
  - openssh
  - openssl
  - pv
  - qt5
  - wget
  - wrk
  - zsh-history-substring-search

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - clion
  - docker
  #- dropbox # for now installed manually via c24 sc
  #- firefox # for now installed manually via c24 sc
  - goland
  - handbrake
  - insomnia
  - intellij-idea
  - kdiff3
  #- keepassxc # for now installed manually via c24 sc
  - libreoffice
  - licecap
  - meld
  - nextcloud
  - postman
  - pycharm
  - sequel-ace
  - stay
  #- slack # for now installed manually via c24 sc
  - transmit
  - visual-studio-code
  - yubico-yubikey-manager
  #- zoom # for now installed manually via c24 sc

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Set to 'true' to configure Sublime Text.
configure_sublime: false

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
