---
- name: config bash_profile
  blockinfile:
    state: present
    mode: '0644'
    path: "~/.bash_profile"
    block: |
      if [ -f /usr/share/bash-completion/completions/git ]; then
          source /usr/share/bash-completion/completions/git
      fi

      # enable color support of ls and also add handy aliases" > .bash_aliases
      if [ -x /usr/bin/dircolors ]; then
        alias grep='grep --color=always'
        alias fgrep='fgrep --color=always'
        alias egrep='egrep --color=always'
        alias pcregrep='pcregrep --color=always -M'
      fi

      # preserves colors, e.g. from grep output
      alias less='less -r'

      # enable sudo to be used together with aliases
      alias sudo='sudo '

      # convenience
      alias ..='cd ..'
      alias df='df -h'
      alias l='LANG=C ls -AHhlF'
      #alias g='git'
      #alias gs='git status -s'
      #alias gr='[! -z `git rev-parse --show-cdup`] && cd `git rev-parse --show-cdup || pwd`'
      alias rsync='rsync -vP'
      alias rsynca='rsync -vPa'

      # vim for large files
      alias vimlarge='vim -u "NONE" -c "set ruler"'

      # tar's impossible to remember parameters..., you just need to add -x / -c for extract / compress
      # commented-out what isn't yet working on mac
      #alias targz='tar -I pigz -xf'
      #alias targz-c='tar -I pigz -cf'
      alias tarxz='tar -xJf'

      export PATH="$HOME/Library/Python/3.9/bin:/opt/homebrew/bin:$HOME/bin:$PATH"
      #export SSH_AUTH_SOCK="$HOME/.ssh/agent"
      export SSH_SK_PROVIDER=/usr/local/lib/libsk-libfido2.dylib

      # autocompletion for ssh host aliases, only needed on Mac
      _ssh()
      {
          local cur prev opts
          COMPREPLY=()
          cur="${COMP_WORDS[COMP_CWORD]}"
          prev="${COMP_WORDS[COMP_CWORD-1]}"
          opts=$(grep '^Host' ~/.ssh/config ~/.ssh/config.d/* 2>/dev/null | grep -v '[?*]' | cut -d ' ' -f 2-)

          COMPREPLY=( $(compgen -W "$opts" -- ${cur}) )
          return 0
      }
      complete -F _ssh ssh

- name: config zshrc
  blockinfile:
    state: present
    mode: '0644'
    path: "~/.zshrc"
    block: |
        export SSH_SK_PROVIDER=/usr/local/lib/libsk-libfido2.dylib

